// src/services/api.js
const BASE_URL = process.env.REACT_APP_API_URL || "http://localhost:5000/api";

export async function generateTestCases(input) {
  const res  = await fetch(`${BASE_URL}/generate-testcases`, {
    method:  "POST",
    headers: { "Content-Type": "application/json" },
    body:    JSON.stringify(input),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data?.error || `Request failed: ${res.status}`);
  return data;
}

// Downloads the Excel file generated by the backend (exact client format)
export async function exportExcel(result, userStory) {
  const res = await fetch(`${BASE_URL}/export-excel`, {
    method:  "POST",
    headers: { "Content-Type": "application/json" },
    body:    JSON.stringify({ result, userStory }),
  });

  if (!res.ok) {
    const err = await res.json();
    throw new Error(err?.error || "Export failed");
  }

  // Trigger download
  const blob     = await res.blob();
  const url      = URL.createObjectURL(blob);
  const a        = document.createElement("a");
  a.href         = url;
  a.download     = `${(result.featureName || "test-cases").replace(/\s+/g, "_")}.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function checkHealth() {
  const res = await fetch(`${BASE_URL}/health`);
  return res.json();
}